### ISSUE TITLE
nzxt-kraken2: fan/pump control

### ISSUE THREAD

**Issue by amezin** [liquidctl/liquidtux#11]
I do not have the device, I've just read the commit message https://github.com/torvalds/linux/commit/82e3430dfa8c32f35ce24a5c628e3e221f168769.

> Fan and pump control, while supported by the devices, are not currently
exposed.  The firmware accepts up to 61 trip points per channel
(fan/pump), but the same set of trip temperatures has to be maintained
for both; with pwmX_auto_point_Y_temp attributes, users would need to
maintain this invariant themselves.

pwm controls don't have to match fan channels. You could expose just one pwm channel that controls both the pump and the fan. pwmconfig should accept this as far as I understand: it tries to detect which fan is controlled by which pwm, so it will probably pick either fan or pump randomly.

**Comment by jonasmalacofilho** [comment]
That's true, and it hadn't occurred to me to expose a single channel for both.  But I'm not sure that it would be nice to use.

With my slower Noctuas it would probably be ok, but with the stock and super loud fans I don't think a single curve for both pump and fans is very reasonable: either the pump would need to run too slow, or the fans too fast&loud.

Because of that, using liquidctl still seems like a better solution, since it allows setting up both curves quasi-independently.  And it may be installed anyway for LED control.  By the way, liquidctl solves the problem by using a fixed set of trip temperatures, and interpolating the user-supplied curves over it.

**Comment by amezin** [comment]
I misunderstood it a bit. There are no trip points in the protocol at all. In this case - yes, hwmon interface isn't flexible enough, and mapping between trip points and the curve that the device expects is probably too complex, not worth it.
