### ISSUE TITLE
X63 support

### ISSUE THREAD

**Issue by minego** [liquidctl/liquidtux#7]
I'd like to be able to access the liquid temperature reported by my Kraken X63, so I can see it with the sensors command and use it as an input for fancontrol.

**Comment by jonasmalacofilho** [comment]
While the X3 coolers are supported by liquidctl, the protocol is not very well understood.  And hwmon kernel drivers work in a significantly different manner than liquidctl.

It's very likely that a lot of experimentation will be necessary, and I don't have one of these devices.  But if you're willing to be the main author of the driver, I can certainly help.

**Comment by minego** [comment]
I'll see what I can do. I looked over the code in both liquidctl and the current hwmon driver... I'll try to spend some time experimenting over the next few days.

**Comment by jonasmalacofilho** [comment]
@minego have you been able to take a look at the code in the [`kraken3-basic-x3-support`](https://github.com/liquidctl/liquidtux/tree/kraken3-basic-x3-support) branch?

By the way, if if seems that no response is every processed, it may be that the check for `STATUS_REPORT_ID` needs to be removed.  Taking a second look at Tom's driver for liquidctl, it's possible that report IDs/numbers are not used by this device.

**Comment by minego** [comment]
I haven't had a chance yet.

**Comment by stalkerg** [comment]
I also interesting in because this device does not support FAN control and we need to emulate somehow FAN control depends on water temp instead of CPU temp. It's why this driver very important.

**Comment by stalkerg** [comment]
nzxt-kraken3 driver looks very simple, I can help you.

**Comment by stalkerg** [comment]
@jonasmalacofilho not really work:
```
kraken3-hid-3-4
Adapter: HID adapter
Pump:             N/A
Coolant:          N/A  
```

**Comment by stalkerg** [comment]
Ok, I can see only one and wrong raw event:
`size:64 id:0x71 data15:0x0 data16:0x1`
looks like we wrongly init the device.

**Comment by stalkerg** [comment]
ok, I know why... let's test it

**Comment by stalkerg** [comment]
it's working! I will make PR.
```
kraken3-hid-3-4
Adapter: HID adapter
Pump:        1869 RPM
Coolant:      +31.9°C 
```

**Comment by stalkerg** [comment]
@jonasmalacofilho I am interesting in upstream it.

**Comment by jonasmalacofilho** [comment]
That's great, @stalkerg!

Let me know if you need help preparing or sending the patch.

**Comment by jonasmalacofilho** [comment]
Actually, don't we want to implement pump control on this driver before upstreaming it?

The older Kraken X2 coolers had some limitations that made fan/pump control unsuitable for a hwmon driver, but I don't think this necessarily applies anymore for X3 [and later Z3] coolers.

**Comment by stalkerg** [comment]
> Actually, don't we want to implement pump control on this driver before upstreaming it?

Yes, we can try, but we should put some time limits. I mean, upstreaming still much more important than pump control. 
Also, as I understand, the liquidctl didn't use direct control for PWM(?).

**Comment by jonasmalacofilho** [comment]
> Also, as I understand, the liquidctl didn't use direct control for PWM(?).

Do you mean that we set a PWM x temperature control curve?  If so, that's correct, but the hwmon subsystem supports that as well; the hwmon documentations refers to those as "auto points".

Additionally, it's possible that the device also features a "direct" mode,  The previous generation (X2) does, albeit with some caveats.

**Comment by stalkerg** [comment]
auto points look tricky, we should create a custom attribute group... also currently we write (59+1)-20 = 40 points what unusual for hwmon because for each point we create two sysfs files.

**Comment by jonasmalacofilho** [comment]
> auto points look tricky, we should create a custom attribute group...

The hwmon documentation explicitly instructs _avoiding_ custom attributes.

> for each point we create two sysfs files

I don't follow.

> We can also use interpretation but in that case, we should decide how many points we want to see and it will be static.

I don't think that's necessary, as the available set of points _at the protocol level_ is static.

**Comment by stalkerg** [comment]
> The hwmon documentation explicitly instructs avoiding custom attributes.

At the same time, I can't find examples with auto points and without custom attributes. 

> I don't think that's necessary, as the available set of points at the protocol level is static.

I hope too but again, usually, all other drivers have ~4-5 points maximum but now we should provide 40.

**Comment by jonasmalacofilho** [comment]
> At the same time, I can't find examples with auto points and without custom attributes. (I checked probably all drivers) 

I didn't know that.

What custom attributes do you have in mind?

And it might be worth discussing on the hwmon mailling list about this before working on the actual patch.

**Comment by stalkerg** [comment]
> And it might be worth discussing on the hwmon mailling list about this before working on the actual patch.

yes, it's a good idea, probably it's possible just a lack of documentation this auto point is not so popular thing in hwmon.

**Comment by aleksamagicka** [comment]
Both sensors and curves have been implemented for some time for the X63 and others. I think that this issue can be closed?

**Comment by stalkerg** [comment]
I think so, but I would like to check "write" function. I will try to do it today.

**Comment by stalkerg** [comment]
Okey seems like if we have already `pwm1_enable` is 1 we produce an error if we try to set it again, I suppose it's wrong behavior.

**Comment by stalkerg** [comment]
even if I fixed set too small and too big values (instead return an error we must set such boundary), I still have issues:
![изображение](https://user-images.githubusercontent.com/1853716/210691443-f57bf796-66c5-4ec9-ba8e-19659a78f0d1.png)

Basically, fan2go can't measure the correlation between RPM and PWM.

**Comment by stalkerg** [comment]
okey, we have two issues:
1. internally, it's a percentage, which means the write value is not equal to the read value in many cases. 
2. we a getting the PWM update value with significant delay, userspace apps expected what if they did `write` they can immediately `ready` basically write should be a sync operation.

**Comment by aleksamagicka** [comment]
Thanks, I'll look into it. For values `0-50`, that's because the firmware mandates that the minimum duty for the pump is 20%.

**Comment by stalkerg** [comment]
thanks, yes, I understand, but PWM from userspace should be "virtual" (from my point of view). If I settle 20, I should read 20 even if the device receives 50 instead or any other valid minimum value. 
Basically, only the correlation between PWM and RPMs can be not linear and working async (e.g., RPM will be reached after some time after settled PWM)

**Comment by aleksamagicka** [comment]
The PWM is converted from the duty which is read directly from the device, we can't lie about it.

**Comment by jonasmalacofilho** [comment]
@stalkerg,

> 1. internally, it's a percentage, which means the write value is not equal to the read value in many cases.

Do you remember an exact instance of this happening, and what were both of the values (written and read back) in question?

---

> 2. we a getting the PWM update value with significant delay, userspace apps expected what if they did write they can immediately ready basically write should be a sync operation.

> thanks, yes, I understand, but PWM from userspace should be "virtual" (from my point of view). If I settle 20, I should read 20 even if the device receives 50 instead or any other valid minimum value. [...]

I agree with @aleksamagicka that the driver should present the current PWM value (as) reported by the device.

And my interpretation of the hwmon sysfs ABI is that it would be wrong for userspace to expect otherwise, since _hwmon drivers should match device behavior and state as closely as possible._

**Comment by aleksamagicka** [comment]
> internally, it's a percentage, which means the write value is not equal to the read value in many cases.

I see I didn't explain this. @stalkerg is referring to the cases when you write (for example) `229` into `pwm1` and get `230` when you read it back. That's due to how `DIV_ROUND_CLOSEST()` is behaving with the data its given.

`229` on a pure PWM->[0, 100] scale is `89.803... %`. The device however only accepts integer percentages, so that's rounded to `90%`. When reading that back, we get `90*255/100`, which is `229.5`, and since we can't have decimal values in hwmon that gets rounded to `230`.

This happens because the devices don't offer enough precision for the percentage, and in that case mapping between 0-100 range and 0-255 range can't be completely retained. In the case of Aquacomputer devices and the aquacomputer_d5next driver, centi-percents are used, so the calculation looks like this:

`229` is converted into `229*(100*100)/255 = 8980` and that's written to the device. When we read `8980` back, it's converted to PWM: `8980*255/(100*100) = 228.99`, which is rounded to `229`, the exact value we started with because we have a tighter mapping with more precision.

**Comment by jonasmalacofilho** [comment]
@aleksamagicka, oh, that makes sense. Thanks for the explanation.

**Comment by jonasmalacofilho** [comment]
Closing: we can't address @stalkerg's point #1 (it's a device limitation), and we don't think we should change things regarding point #2.

**Comment by stalkerg** [comment]
@jonasmalacofilho 
>  hwmon drivers should match device behavior and state as closely as possible.

Can you point this into documentation or so? I need arguments for the fan2go developer. He made the daemon and program from entirely different assumption.

**Comment by amezin** [comment]
@aleksamagicka 

> The PWM is converted from the duty which is read directly from the device, we can't lie about it.

@jonasmalacofilho 

> and we don't think we should change things regarding point #2.

Actually, nzxt-smart2 driver does "lie" about pwm a bit: https://github.com/liquidctl/liquidtux/blob/master/nzxt-smart2.c#L490-L503 Yes, the version in the kernel tree too: https://github.com/torvalds/linux/blob/master/drivers/hwmon/nzxt-smart2.c#L484-L497

Because otherwise pwmconfig and fancontrol don't work well (see the comment).

**Comment by jonasmalacofilho** [comment]
@amezin,

> Actually, nzxt-smart2 driver does "lie" about pwm a bit:

https://github.com/liquidctl/liquidtux/blob/8524d61785690e0b14df66facc6a843dc1912cbb/nzxt-smart2.c#L490-L503

Oh, I forgot about that. Thanks for reminding us.

@aleksamagicka, in light of that, do you want to do the same here?

Additionally, ccording to that comment, the issue also affects fancontrol, which is more or less the cannonical userspace for hwmon PWM control.

---

@stalkerg,

Please disregard that statement. I can't find anything the hwmon documentation to really back that up... maybe the I got that impression from watching the mailing list, or maybe I'm just plainly wrong.

**Comment by amezin** [comment]
Although the comment isn't accurate... nzxt-smart2 performs rounding too, so you won't always read back exactly the same pwm value you've written. And if you changed it by just 1 or 2, you may read the same value - the difference might be lost during the conversion to percent and back.

But when the userspace changes the value significantly, the driver should respond - i. e. after `write()` returned to userspace, all `read()`s should read a new changed value.

At least that's what was necessary to make fancontrol behave reasonably well.

**Comment by stalkerg** [comment]
Sorry, I want to add a more general topic:
The hwmon it's an abstraction interface from sensors and fan controls in the kernel into userspace. How is it possible to write an effective userspace application if this API behavior very depends on a specific driver and specific hardware behavior? 
Sorry, but fancontrol working is much more stable because it's primitive. https://github.com/markusressel/fan2go doing much more interesting things and much more accurate from user's point of view. 
But even fancontrol can't work properly if hwmon drivers can't keep consistent behavior. Yes, we can leave with rounded numbers but it will be better to work without them. 
Also, set value 0 never should provide error, it should set a minimum value! fan2go just break on it and I suppose pwmconfig can as well (both trying to check pwm/fan rpm dependencies just increase numbers from 0 to 255, and if found error stops the process (what else they should do?))

I also fixed a similar bug with rounded in amdgpu for vega (they did even more - simulate PWM based on RPM and depend on firmware it show noise). 
hwmon API should provide more consistent high-level API, current just has no sense for userspace. 

Sorry, for the "offtopic" and some emotions.

**Comment by aleksamagicka** [comment]
Ah, had no idea that was allowed. Thanks for the pointer in nzxt-smart2.

Noted on the 0, will look into that as well. Reopening for now.
